### ISSUE TITLE
Can't compile with GHC 9.2.1

### ISSUE THREAD

**Issue by LeventErkok** [sjakobi/newtype-generics#20]
```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.2.1
```

and later:

```
Configuring library for newtype-generics-0.6..
Preprocessing library for newtype-generics-0.6..
Building library for newtype-generics-0.6..
[1 of 1] Compiling Control.Newtype.Generics

Control/Newtype/Generics.hs:68:61: error:
    Module ‘Data.Semigroup’ does not export ‘Option(..)’
   |
68 | import Data.Semigroup (Min(..), Max(..), WrappedMonoid(..), Option(..))
   |                                                             ^^^^^^^^^^
```

**Comment by LeventErkok** [comment]
```
Configuring library for newtype-generics-0.6..
Preprocessing library for newtype-generics-0.6..
Building library for newtype-generics-0.6..
[1 of 1] Compiling Control.Newtype.Generics

Control/Newtype/Generics.hs:68:61: error:
    Module ‘Data.Semigroup’ does not export ‘Option(..)’
   |
68 | import Data.Semigroup (Min(..), Max(..), WrappedMonoid(..), Option(..))
   |                                                             ^^^^^^^^^^
```

**Comment by LeventErkok** [comment]
Ah, I see there's a PR by @TomMD addressing this. Hope it gets released soon!

**Comment by sjakobi** [comment]
https://hackage.haskell.org/package/newtype-generics-0.6.1 is on Hackage now.
